Module4 task1
htmlacademy-adaptive/1827831-sedona-27 pull request #4
Opened 2022-12-26 15:56 UTC by VikaVikovna

2022-12-26 16:27 UTC, DoberBober commented on source/index.html
> +        <li class="main-header__navigation-section">Главная</li>
Ссылки внутри лишек потерялись.

2022-12-26 16:28 UTC, DoberBober commented on source/index.html
>                  <img src="../../img/icon-house.svg" width="40" height="40" alt="Дом.">
Здесь и далее: в подключениях картинок поправить урл: `src="./img/XXX"`.

2022-12-26 16:29 UTC, DoberBober commented on source/index.html
> +            <li class="advice__item advice__item&#45;&#45;house">
Здесь и у следующих двух лишек: замени спецсимволы на обычные дефисы.

2022-12-26 16:29 UTC, DoberBober commented on source/index.html
> +    </ul>
Не разделяй. Это один список, не два.

2022-12-26 16:30 UTC, DoberBober commented on source/less/blocks/action.less
> +@media (min-width: 768px) and (max-width: 1200px) {
Ты значения вьюпортов вынесла в переменные, но не используешь их.

2022-12-26 16:32 UTC, DoberBober commented on source/less/blocks/advice.less
> +
Старайся писать один раз селектор и внутри него медиа. Типа такого:
```
.advice__list{
    ...
    @media(min-width: @tablet){
    ...
    }
    @media(min-width @desktop){
    ...
    }
}
```

2022-12-26 16:32 UTC, DoberBober commented on source/less/blocks/main-container.less
> +  background: url("../../img/background-image.png") no-repeat center;
`url("../img/XXX")`.

2022-12-26 16:33 UTC, DoberBober commented on source/less/blocks/main-container.less
> +  .main-image {
Файл называется main-container, а стили для main-image лежат.

2022-12-26 16:33 UTC, DoberBober commented on source/less/blocks/viewports.less
> +@tablet-width: 768px;
Удали этот файл. У тебя ж есть уже файл с переменными (variables).

2022-12-26 16:35 UTC, DoberBober commented on source/less/global.less
>  .page__body {
Для страницы пропиши ширину как в макете на разных разрешениях и маргин 0 авто, чтобы отцентровать.

2022-12-26 16:36 UTC, DoberBober requested changes
По самой сетке не так много вопросов. Картинка сползла и внизу пункты 3, 4, 5 не вколонки стоят.
![image](https://user-images.githubusercontent.com/18398812/209568231-8d24453f-2d9b-41f9-bfed-63903f7ae854.png)

2022-12-26 18:35 UTC, VikaVikovna commented on source/index.html
> +        <li class="main-header__navigation-section">Главная</li>
Добавила с заглушкой #

2022-12-26 18:39 UTC, VikaVikovna commented on source/index.html
>                  <img src="../../img/icon-house.svg" width="40" height="40" alt="Дом.">
поправила в index

2022-12-26 18:39 UTC, VikaVikovna commented on source/index.html
> +            <li class="advice__item advice__item&#45;&#45;house">
сделано

2022-12-26 18:54 UTC, VikaVikovna commented on source/index.html
> +    </ul>
убрала, у ul добавила display flex и flex-wrap wrap

2022-12-26 19:05 UTC, VikaVikovna commented on source/less/blocks/action.less
> +@media (min-width: 768px) and (max-width: 1200px) {
заменила во всем файле на переменные

2022-12-26 19:06 UTC, VikaVikovna commented on source/less/blocks/main-container.less
> +  background: url("../../img/background-image.png") no-repeat center;
поменяла

2022-12-26 19:08 UTC, VikaVikovna commented on source/less/blocks/main-container.less
> +  .main-image {
Создала новый файл main-image.less

2022-12-26 19:14 UTC, VikaVikovna commented on source/less/blocks/viewports.less
> +@tablet-width: 768px;
Удалила

2022-12-26 19:23 UTC, VikaVikovna commented on source/less/blocks/advice.less
> +
Когда так пишу, подчеркивает красным media

2022-12-26 19:24 UTC, VikaVikovna commented on source/less/global.less
>  .page__body {
прописала

2022-12-26 19:28 UTC, DoberBober commented on source/less/blocks/advice.less
> +
А что пишет, когда наводишь на подчеркивание?

2022-12-26 19:30 UTC, VikaVikovna commented on source/less/global.less
>  .page__body {
Всё сломалось, после этого кода:
.page__body {
  margin: 0;
  font-family: "PT Sans", sans-serif;
}

@media (min-width: @desktop-width) {
  .page__body {
    width: 1200px;
    margin: 0 auto;
  }
}

@media (min-width: @tablet-width) {
  .page__body {
    width: 768px;
    margin: 0 auto;
  }
}

2022-12-26 19:30 UTC, VikaVikovna commented on source/less/global.less
>  .page__body {
Что не так?

2022-12-26 19:34 UTC, DoberBober commented on source/less/global.less
>  .page__body {
Медиа пиши от меньшего к большему. Сначала таблет, потом комп. margin 0 auto пропиши на самом верху, вне медиа. А внутри - удали. В терминале есть ошибки? Что именно сломалось?

2022-12-29 09:24 UTC, DoberBober approved these changes
lgtm.

2022-12-29 09:24 UTC, merged