Адаптивная графика
htmlacademy-adaptive/1827831-sedona-27 pull request #6
Opened 2023-01-09 12:36 UTC by VikaVikovna

2023-01-09 15:29 UTC, DoberBober commented on source/less/blocks/advantage.less
> +  @media (min-resolution: 2dppx) {
Это ж тег `img`. 2x-версии через разметку подключаются.

2023-01-09 15:29 UTC, DoberBober commented on source/less/blocks/main-image.less
> +    background-image: url("../img/main-image-2x.jpg");
Только для планшета подключила. Надо ещё на телефоне и компе тоже.

2023-01-09 15:32 UTC, DoberBober requested changes
Тень по краям сайта на планшетке тоже подключи, так как у тебя планшетная версия не резиновая, в отличии от мобилки, а фиксированная и всегда по центру.

Как сделаешь, скидывай на повторную. В следующем задании уже начинай делать пиксель тоже. Сверху вниз, от мобилки к компу.

2023-01-10 19:20 UTC, DoberBober commented on source/index.html
> +            <img src="./img/photo-city-mobile.jpg" width="520" height="260" alt="Фото моста." class="advantage__section-img">
1. Сначала 1x, потом 2x.
2. У тега img забыла прописать srcset с 2x картинкой. Обрати внимание, что у img обозначать плотность стандартной картинки через 1x не надо. 2x надо.

2023-01-10 19:20 UTC, DoberBober commented on source/index.html
> +            <img src="./img/bridge-image-mobile.jpg" width="520" height="260" alt="Фото моста.">
Тут тоже.

2023-01-10 19:20 UTC, DoberBober requested changes
Не спеши.

2023-01-11 06:22 UTC, VikaVikovna commented on source/index.html
> +            <img src="./img/photo-city-mobile.jpg" width="520" height="260" alt="Фото моста." class="advantage__section-img">
То есть должно выглядеть так?

<picture>
            <source media="(min-width: 1200px)" srcset="./img/photo-city-desktop@1x.jpg 1x, ./img/photo-city-desktop@2x.jpg 2x">
            <source media="(min-width: 768px)" srcset="./img/photo-city@1x.jpg 1x, ./img/photo-city-tablet@2x.jpg 2x">
            <img src="./img/photo-city-mobile.jpg" srcset="./img/photo-city-mob-2x.jpg 2x" width="520" height="260" alt="Фото моста." class="advantage__section-img">
          </picture>

2023-01-11 11:25 UTC, merged