Оптимизация графики
htmlacademy-adaptive/1827831-sedona-27 pull request #7
Opened 2023-01-15 19:50 UTC by VikaVikovna

2023-01-15 20:01 UTC, DoberBober commented on source/index.html
> +<svg style="display: none">
Весь спрайт должен быть собран в один svg, но, учитывая, что впереди лекция по автоматизации, эт оможно пропустить.

2023-01-15 20:02 UTC, DoberBober commented on source/index.html
> +            <source type="image/webp" media="(min-width: 768px)"
Парсер ищет первый подходящий сурс. Сначала 1200, потом 768.

2023-01-15 20:03 UTC, DoberBober commented on source/index.html
> +
Какой-то symbol лишний.

2023-01-15 20:09 UTC, DoberBober requested changes
1. На мобилке `main-image` сломался.
2. Если увеличить чуть мобилку, сайт "расползается".  Пропиши ширину у body, отцентрируй, выведи по краям тень.
3. Мобильное меню открытое чуть кривовато (полоски странные).

Планшет:
1. Пункты меню в две строки.
2. Белая фигура над main-image съехала (её бычерез псевдо вывести).
3. Картинка слева от "Настоящий городок".
4. Под advantage__section-grey-background есть полоски.
5. Цвет иконки копирайта.

Комп:
1. Ширина у body 1200px.

При наведении на копирайт, меняется отдельно цвет текста и отдельно иконка.

Сам пиксель пока не проверял.

2023-01-16 20:08 UTC, VikaVikovna commented on source/index.html
> +            <source type="image/webp" media="(min-width: 768px)"
Здесь не поняла - нужно поменять местами?

2023-01-16 20:28 UTC, DoberBober commented on source/index.html
> +            <source type="image/webp" media="(min-width: 768px)"
Да. Сначала 1200 вебп, потом 768 вебп, мобилка вебп. Потом 1200 jpg, 768 jpg, мобилка jpg.

2023-01-17 11:06 UTC, VikaVikovna commented on source/index.html
> +            <source type="image/webp" media="(min-width: 768px)"
а если оставить min-width: @tablet, ведь это касается и десктопа тоже. Или там отдельные картинки должны быть?

2023-01-17 11:34 UTC, DoberBober commented on source/index.html
> +            <source type="image/webp" media="(min-width: 768px)"
Если в данном случае планшетная подходит и для компа, можешь оставить только таблет.

2023-01-20 16:49 UTC, merged